const TYPE = {
    HIDE_TABBAR_MUTATION:'HIDE_TABBAR_MUTATION',
    SHOW_TABBAR_MUTATION:'SHOW_TABBAR_MUTATION',
    M_FILM_ADERTISEMENT:'M_FILM_ADERTISEMENT',
    M_FILM_NOWPLAYING:'M_FILM_NOWPLAYING',
    M_FILM_CURRENT:'M_FILM_CURRENT',
    M_FILM_NOWPLAYINGLENGTH:'M_FILM_NOWPLAYINGLENGTH',
    M_FILM_COMMINGLIST:'M_FILM_COMMINGLIST',
    M_DETAIL:'M_DETAIL',
    M_CINEMA_LIST:'M_CINEMA_LIST',
    M_SHOW_CINEMA_DITAIL:'M_SHOW_CINEMA_DITAIL',
    M_Hide_CINEMA_DITAIL:'M_Hide_CINEMA_DITAIL',
    M_SAVE_CINEMA_LIST:'M_SAVE_CINEMA_LIST',
    M_CINEMA_LIST_COUNTER:'M_CINEMA_LIST_COUNTER',
    M_SAVE_COUNTER_LIST:'M_SAVE_COUNTER_LIST',
    M_CITY_LIST:' M_CITY_LIST',
    M_GPSCITY_ID:'M_GPSCITY_ID',
}

export default TYPE;